README.md
autotable/processor/analysis.py
tests/test_analysis.py
tests/test_type.py

add some test

---

autotable/__main__.py
autotable/api/prs.py
autotable/processor/analysis.py
autotable/processor/github_stats.py
tests/test_analysis.py

add issue_update_stats arg

---

.github/renovate.json5

add renovate

---

README.md
autotable/__main__.py
autotable/processor/file.py

修复内容替换部分
修复在没有 bot 标签的时候不替换内容
更新 readme

fix replace table and ignore bot tag

---

autotable/command.py

fix f-string

---

.github/renovate.json5

fast renovatebot

---

.github/workflows/build.yml
README.md
autotable/__main__.py
autotable/command.py
autotable/constant.py
autotable/processor/file.py
autotable/utils/fetcher.py

添加自检查
* 日志文件路径
* 备份文件路径
* Github 连接检查
```bash
autotable doctor
[✓] Data dir path: /Users/***/Library/Application Support/autotable, size: 0.000M
[✓] Log dir path: /Users/***/Library/Logs/autotable, size: 0.118M
[✓] Github resources
```
* `pathlib` 对非空文件夹 clean error
* 保存文件使用`utf-8`
* 修改`dry_run`存储位置为当前运行目录

add doctor

---

autotable/__main__.py
autotable/processor/github_stats.py

* 修复已删除任务的状态统计
* `doctor` 追加报错信息

fix delete task

---

autotable/processor/github_issue.py
autotable/processor/github_prs.py
autotable/processor/github_stats.py

修复删除线不规范的问题，必须为双波浪线，并添加检查
不规范：`~`
规范：`~~`

fix Strikethrough

---

autotable/autotable_type/autotable_type.py
autotable/autotable_type/github_type.py
autotable/processor/github_issue.py
autotable/processor/github_prs.py
tests/test_type.py

拆分认领和提 pr 的两种状态，新的认领状态为 `🙋` 符号

change `CLAIMED` and add `REPAIRING`

---

.pre-commit-config.yaml

update ruff v0.3.4

---

pyproject.toml

update version v0.2.0beta

---

TODO.md
autotable/__main__.py
autotable/api/issues.py
autotable/api/prs.py
autotable/command.py
autotable/model/tracker_issues_data.py
autotable/processor/github_issue.py
autotable/utils/fetcher.py
pyproject.toml

* 添加 `Fetcher` 为空检查
* 修改 `Matching failed` 日志等级
* 添加更多 TODO

♻️  chore: code organization

---

pdm.lock
pyproject.toml

⬆️ deps: Update dependencies

---

autotable/processor/github_title.py
autotable/utils/strtool.py
tests/test_github_title.py

`titleBase` 初始化的时候，先把 title 统一格式化，再做处理，如：
```
A15 转换为 A-15
A+2,A*4，A - 1、A- 24,A234\a432 转换为 A-2,A-4,A-1,A-24,A-234,A432
A-[48-52] 转换为 A-48,A-49,A-50,A-51,A-52
```

✨ feat: add clean and format title before process

---

README.md
TODO.md
autotable/api/issues.py
autotable/command.py
autotable/model/tracker_issues_data.py
autotable/processor/analysis.py
autotable/processor/github_prs.py
tests/test_analysis.py

* 支持使用其他仓库搜索 pull
生成后 demo:
```md
| 序号   | 文件                            | API 数量 | 认领人 Github id | PR 链接                                             |
| ---- | ----------------------------- | ------ | ------------- | ------------------------------------------------- |
| ✅A-1 | paddle/tensor/array.py        | 4      | ✅@gouzil     | https://github.com/gouzil/autoTable/pull/1 |
```
* pr 标题匹配异常
demo:
```python
import re
title_re = r"\[Typing\]\[(?P<task_id>[\S\s]+)\]"
title = "🚧[Typing][A-48,A-49,A-50,A-51] Add type annotations for `paddle/optimizer/*`"
print(re.match(title_re, title)) # output: None
print(re.search(title_re, title).group()) # output: [Typing][A-48,A-49,A-50,A-51]
```

✨ feat: supper remote repo

---

.pre-commit-config.yaml

⬆️ deps: Update ruff v0.4.8

---

autotable/processor/github_issue.py
autotable/processor/github_prs.py
autotable/processor/utils.py
tests/test_github_issue.py
tests/test_storage_model.py

修复了认领人不会换行的bug
demo:
```
✅@gouzil🙋@undefined<br/>
```

🐛 fix: more people claimed error

---

README.md
autotable/command.py
autotable/processor/analysis.py
autotable/processor/github_prs.py
autotable/utils/fetcher.py
tests/test_analysis.py

支持在指定 repo 中支持多 repo
```md
单repo
多repo
```
修复了标题序号解析错误
```md
正常写法
[Typing][A-1] ....
常见，但不应该解析的写法
[Typing][Fix] ....
```

✨ feat: supper specify multiple repos

---

README.md

🐛 fix: readme

---

README.md
autotable/__main__.py
autotable/command.py
autotable/processor/github_prs.py
autotable/storage_model/tracker_issues_data.py
autotable/utils/migrate.py
pyproject.toml
tests/test_migrate.py

* 修改了新的pr url 表示方式 -> `gouzil/autoTable#1`
这一改动将不再限制 url 的形态，更多的取决于用户, 以下两种形式均有可能
gouzil/test#1
gouzil/autoTable#1
* 同时增加了快速迁移command `autotable migrate02to03`

🍻 feat: change pr url format

---

autotable/processor/github_prs.py

修复了之前重复显示错误解析 title 的问题
现在统一成了一次`warning`

🐛 fix: duplicate log

---

TODO.md
autotable/constant.py
autotable/processor/github_prs.py
autotable/storage_model/pull_data.py
autotable/utils/fetcher.py

* 最开始缓存这个数据是因为每次调用`get_reviews`都会有一次请求，现在已经不需要了。现在的缓存会在`get_pr_list`一次建立

🔥 clean: Delete unnecessary caches

---

autotable/api/issues.py
autotable/processor/github_issue.py
autotable/storage_model/tracker_issues_data.py

* 为 issue 添加中间表示层
* 猜猜这次有多少性能提升 (答案在照片里)

♻️ reconfiguration:Add an intermediate presentation layer to the issue

---

autotable/autotable_type/github_type.py
pyproject.toml
tests/test_analysis.py
tests/test_type.py
tests/test_update_issue_table.py
tests/test_update_pr_table.py
tests/test_update_stats.py

🧪 test: add more processor test

---

.github/workflows/build.yml
README.md
autotable/__main__.py
autotable/api/issues.py
autotable/api/prs.py
autotable/command.py
autotable/processor/analysis.py
autotable/storage_model/tracker_issues_data.py
autotable/utils/fetcher.py
pdm.lock
pyproject.toml
tests/test_analysis.py

* 更换了一个支持异步的 API 库, 并把 pr 请求部分全部改为并行。
* 新增 pull 开始时间配置 ``

⚡ ✨ api: support async and add `start_pull_time` config

---

autotable/api/prs.py

🐛 fix: update pull request search query to include pull requests created on start time

---

.github/workflows/build.yml

👷 chore: optimize parallel execution in build and tests workflows

---

.github/renovate.json5

👷 chore: update renovate.json5 with parallel execution

---

autotable/__main__.py
autotable/api/prs.py
autotable/command.py
autotable/processor/analysis.py
autotable/processor/utils.py
pyproject.toml

* 修复在搜索 pull 列表时内容不完整的问题
* 修复`migrate02to03`和`doctor`命令设置 repo 错误的问题
* 新增初始化 issue 任务表格 ( 暂不支持统计表格的初始化 )
* `issue_update`命令默认会重置 issue 任务表格 ( 如果表格内有手动修改的内容请使用`--no-reset-table` )
* ruff 规则添加 T10

✨🐛  feat: Add the init_issue command and fix search_pull

---

.pre-commit-config.yaml
autotable/processor/github_title.py

⬆️ ruff: update to v0.5.0

---

tests/test_init_issue_table.py

#49 `init_issue` command 测试文件忘记上传了

🧪 init_issue: add test

---

README.md
autotable/api/prs.py
autotable/command.py
autotable/processor/analysis.py
tests/test_analysis.py

* 允许用户追加搜索条件
```md
原有搜索条件为: is:pr repo:gouzil/autoTable created:>=2024-06-10
追加后搜索条件为: is:pr repo:gouzil/autoTable created:>=2024-06-10 /\[Typing\]/
```
close: #52

✨ feat: add `pr_search_content` tag

---

.gitignore
.vscode/settings.json

- ignore vscode
- 不在保存时 format （耗时，主要是个人习惯不同 ～ 🫠🫠🫠
（其实，把 vscode 放到 ignore 里面就行了 ～～～ 🫠🫠🫠

[Change] ignore vscode

---

autotable/processor/github_issue.py

🚑 fix: comment update Strikethrough

---

.github/workflows/build.yml
.pre-commit-config.yaml
autotable/command.py
autotable/processor/analysis.py
autotable/processor/github_issue.py
autotable/processor/github_prs.py
autotable/processor/github_title.py
autotable/processor/utils.py
autotable/utils/fetcher.py
pyproject.toml
tests/test_analysis.py
tests/test_github_title.py
tests/test_migrate.py
tests/test_storage_model.py
tests/test_type.py
tests/test_update_issue_table.py
tests/test_update_pr_table.py
tests/test_update_stats.py

* 升级 ruff 到 v0.5.6
* 增加了一些规则
* 删除 ci 中的最大运行数限制

👷 🎨 ruff: add more rules and update v0.5.6

---

autotable/api/prs.py
autotable/constant.py
autotable/utils/fetcher.py
pyproject.toml

* ruff 添加 `PTH` 规则
* 添加`get_pr_list`的 cache, 缓解 pull 列表为空重复请求的情况

✨ feat: add get pr list cache

---

pyproject.toml

🎉 release 0.3.0

---

.pre-commit-config.yaml
autotable/processor/github_prs.py
pdm.lock
pyproject.toml

* 升级 ruff 到 0.8.2 , 并修复相关问题
* 升级 githubkit 到 0.12.0
* 升级 loguru 到 0.7.2

[dep] update ruff to 0.8.2

---

autotable/api/prs.py
autotable/command.py
autotable/processor/github_issue.py
autotable/processor/github_prs.py
tests/test_update_issue_table.py
tests/test_update_pr_table.py

⚡ use `re.compile` replace `re`
